### ISSUE TITLE
Make lecture 6 notes

### ISSUE THREAD

**Issue by tingting4805** [harvard-ml-courses/cs281-scribe#11]
Hi Guys, 

@tk000
@yling96

I have started a sharelatex project for lecture 6 notes. (i made it public so everyone can edit it... or is there a project on sharelatex?)

https://www.sharelatex.com/project/59c2b7fcb083e60fd6a0a890

Thanks, wenting

**Comment by tingting4805** [comment]
My thoughts on each part would be...

1. introduction to exponential family / two examples
2. three properties.
3. the rest.

What do you think? I will start working on the first part....

**Comment by yling96** [comment]
We already have a doc. Please see https://www.sharelatex.com/project/59c286090193421f18ce973d. Feel free to make changes.

**Comment by tingting4805** [comment]
sorry I just saw your Facebook friend request
 I don't check Facebook regularly.

I will go through the notes ASAP.

**Comment by tingting4805** [comment]
@yling96 
I just made a few changes. It's good to go.

**Comment by rachtsingh** [comment]
Could someone make a pull request?

**Comment by rachtsingh** [comment]
Thanks for getting this done, btw. Here's a walkthrough with steps:

1. Make your own fork (so you can make a pull request).
2. Make a `6/` folder and include in it a copy of `5.tex -> 6.tex`
3. Edit `6.tex` with the lecture notes
4. Edit `main.tex` to add a reference to `6/6` (i.e. `6.tex` inside folder `6/`)  
5. Edit README.md to refer to the right place

Make sure `6/6.pdf` are compiled and committed, and `main.pdf` is recompiled.

**Comment by rachtsingh** [comment]
Thanks!
