### ISSUE TITLE
4th scriber for "Linear Classification"

### ISSUE THREAD

**Issue by fberlinger** [harvard-ml-courses/cs281-scribe#12]
Hey guys,

I am Florian (@fberlinger, fberlinger at seas dot harvard dot edu) and I was supposed to be added earlier as a 4th scriber as per the scribing excel sheet.

The assistants suggested that I proofread what you have so far. Here are my comments:

1) In section 5.2.2 \mu_{jc} is a vector containing several features j as opposed to 5.2.1. I'd emphasize that fact by using vector notation: \vec{\mu}_{jc}.

2) In equation 5.9 I guess we should change subscript i to j as we are summing over all features j.

3) In section 5.4 we might add 2. (d) Inverse-Wishart (Iw) (goes with Normal) as mentioned in class.

4) Language in section 5.5: change "helps prevents" to either "prevents" or "helps preventing".

5) A minor note on Latex style: Quotes are added like ``Hello, I am between two quotation marks''.

Please add me as a fourth author and re-submit.

Thank you so much!
Florian

**Comment by artidoro** [comment]
Hey sorry! I didn't see that
All the comments sound good!
Let me resubmit..
