### ISSUE TITLE
Make Lecture Notes 8

### ISSUE THREAD

**Issue by marikgoldstein** [harvard-ml-courses/cs281-scribe#18]
Hi all, just a reminder to make a pull request together for the lecture 8 notes.

@ganand, Giridhar Anand
@michael-hahn, Xueyuan Michael Han
@anaroxanapop, Ana-Roxana Pop

You'll want to:

Make your own fork (so you can make a pull request).
Make a 8/ folder and include in it a copy of 7.tex -> 8.tex
Edit 8.tex with the lecture notes
Edit main.tex to add a reference to 8/8 (i.e. 8.tex inside folder 8/)
Edit README.md to refer to the right place
Feel free to discuss on here or on ShareLatex if that's easier.

**Comment by rachtsingh** [comment]
thanks mark for poking, looks like it was made here: https://github.com/harvard-ml-courses/cs281-scribe/pull/19. I'll merge after comments fixed, and close this.

**Comment by rachtsingh** [comment]
Done! Thanks everyone.

**Comment by marikgoldstein** [comment]
Hi Everyone,

Good job on the notes. Can you fix a typo in the Gaussian DGM example? At one point it mentions

W_ij ( x_ij - m_j)

I believe the i in x_ij should not be there.  It's a linear transformation of the parent x_j.

Please confirm with the section notes.
