### ISSUE TITLE
Make Lecture 10 Notes: Time Series

### ISSUE THREAD

**Issue by marikgoldstein** [harvard-ml-courses/cs281-scribe#25]
Hi all, just a reminder to make a pull request together for the lecture 10 notes.

@Natmax, Nathaniel (Max) Hopkins,
@lavjams, Jamila Pegues
@swagnercarena, Sebastian Wagner-Carena
@brabeeba, Brabeeba (Mien) Wang

You'll want to:

Make sure you read the [LaTeX Guide](https://github.com/harvard-ml-courses/cs281-scribe/blob/master/scribe_notes.md)
Make your own fork (so you can make a pull request when submitting).
Make a 10/ folder and include in it a copy of 9.tex -> 10.tex (or 8 if 9 is not up)
Edit 10.tex with the lecture notes
**Place all of your added commands + libraries in pagesetup.sty in the main directory**
Edit main.tex to add a reference to 10/10 (i.e. 10.tex inside folder 10/)
Edit README.md to refer to the right place
Feel free to discuss on here or on ShareLatex if that's easier.
**Make sure that main.tex compiles before submitting a pull request**

**Comment by lavjams** [comment]
We've submitted a pull request!  Please let us know if it went through alright (as none of us are very versed in Github.)

**Comment by rachtsingh** [comment]
I don't think it went through :( Can you link me to where you think the PR is?

**Comment by marikgoldstein** [comment]
It went through, I approved it!

**Comment by rachtsingh** [comment]
Oh ok sounds good.
