### ISSUE TITLE
Make Lecture 11 Notes: Belief Propogation

### ISSUE THREAD

**Issue by marikgoldstein** [harvard-ml-courses/cs281-scribe#27]
Hi all, just a reminder to make a pull request together for the lecture 11 notes.

@benatii, Ismail Ben Atitallah
@fullerene12, Hao Wu
@raphaelrk, Raphael Rouvinov
@orekki, Ziliang Che
@jiaoyang, Jiaoyang Huang

You'll want to:

Make sure you read the LaTeX Guide
Make your own fork (so you can make a pull request when submitting).
Make a 11/ folder and include in it a copy of 10.tex -> 11.tex (or 9 if 10 is not up)
Edit 11.tex with the lecture notes
Place all of your added commands + libraries in pagesetup.sty in the main directory
Edit main.tex to add a reference to 11/11 (i.e. 11.tex inside folder 11/)
Edit README.md to refer to the right place
Feel free to discuss on here or on ShareLatex if that's easier.
Make sure that main.tex compiles before submitting a pull request

**Comment by fullerene12** [comment]
Hi Mark,

I have pushed my scribe to my fork. Let me know if there anything I shoud
change/add.

Thank you!

Best,
Hao

**Comment by jiaoyang** [comment]
Hi everyone,

I also pushed my scribe to my fork. I wonder how should we combine those
notes together?

Best,
Jiaoyang.

**Comment by marikgoldstein** [comment]
It was up to all of you to communicate and make one set of scribe notes. Please message each other and take care of this.

**Comment by fullerene12** [comment]
Hi Jiaoyang,

My fork is at:

https://github.com/fullerene12/cs281-scribe.git

You could add my stuff to yours, or I could do combination, let me know! :)

Best,
Hao

**Comment by raphaelrk** [comment]
Hi @marikgoldstein, this caught me off guard. I'm very, very confident I signed up to scribe the Information Theory lecture (this wednesday) and not the one on Belief Propagation, so I wasn't looking out for this. Would it be possible to scribe this wednesday's lecture? If not, I can get this in by tomorrow evening, or comment one of the ipython notebooks.

**Comment by marikgoldstein** [comment]
Sorry Raph, must be an error. Sure, just confirm that your name is listed for whichever lecture you plan to scribe. No need to join this one.

**Comment by jiaoyang** [comment]
Hi everyone,

Let's just combine everything to Hao Wu's repo: @fullerene12 <
https://github.com/fullerene12>.

PS: Hao, I'll combine my file with yours tonight!

Best,
Jiaoyang.

**Comment by jiaoyang** [comment]
Hi everyone,

Do you have any more comments of the attached notes for lecture 11? We can
add it to cs281-scribe tomorrow.

Best,
Jiaoyang.
