### ISSUE TITLE
Lecture 13 Information Theory

### ISSUE THREAD

**Issue by raphaelrk** [harvard-ml-courses/cs281-scribe#29]
Hi all, 

Josh put together a sharelatex for us to contribute our notes to. Link [here](https://www.sharelatex.com/project/59e799350f4eac2ff4820611). Far from complete, let's clean it up / flesh it out and let @marikgoldstein know when we're done.

@joonheechoi Joonhee Choi
@sonhyoungmok Hyungmok Son
@joshim Joshua Meier
@rchen277 Ruiqi Chen
@chang04 Peter Chang

**Comment by raphaelrk** [comment]
Hi all, 

Made a lot of touch ups, would appreciate if you guys went through it and made sure all the content from the lecture is there.

**Comment by rchen277** [comment]
Hi all,

I added the parabola picture, and made some touch ups as well. I caught a
few small errors going through. I think the note would be ready to go with
one more round of proof reading. The style format at the end (page 4) may
still have room for improvement (I'm not good at latex styling XD).

Ruiqi

**Comment by rachtsingh** [comment]
Is this finished? Could you please finish it tomorrow?

**Comment by raphaelrk** [comment]
Made a pull request #30

**Comment by marikgoldstein** [comment]
We pulled it in.
