### ISSUE TITLE
Clean up Lecture 2 notes

### ISSUE THREAD

**Issue by rachtsingh** [harvard-ml-courses/cs281-scribe#3]
We'd like the final form of the lecture notes to be a little cleaner. Examples of things to fix:

1. Change `$$$$ \\` -> `\begin{align}\end{align}` envs.
2. More explanation of what Sasha said (what did he say about Dirichlets? what are they used for?)
3. `p(words)` -> `p(\text{words})`

Since @ashilgard pushed the first version, could the other two people signed up to scribe (@albertw1 + @diondrapeck) tackle this?

**Comment by diondrapeck** [comment]
Of course, I'll work on it tonight!

**Comment by da03** [comment]
Great thanks!

**Comment by diondrapeck** [comment]
I cloned the repo, made changes, and just tried to push, but I'm getting a permission denied error.

**Comment by rachtsingh** [comment]
I think you need to push your fork up to the repo and make a pull request, or make a pull request from your clone.

It's a bunch of work to give everyone in the class write access, basically, and this way we can make sure it's good before merging.
