### ISSUE TITLE
Make lecture 16: Mean Field

### ISSUE THREAD

**Issue by hzshan** [harvard-ml-courses/cs281-scribe#35]
Hi all, just a reminder to make a pull request together for the lecture 16 notes, Advanced Variational Inference.

@denisturcu Denis Turcu
@yaojiayu0826
@sophiesi Xu Si

You'll want to:

Make sure you read the LaTeX Guide
Make your own fork (so you can make a pull request when submitting).
Make a 16/ folder, include in it a copy of 15.tex, and rename it to 16.tex
(use a previous one if 15.tex is not up yet)
Edit 16.tex with the lecture notes
Place all of your added commands + libraries in pagesetup.sty in the main directory
Edit main.tex to add a reference to 16/16 (i.e. 16.tex inside folder 16/)
Edit README.md to refer to the right place
Feel free to discuss on here or on ShareLatex if that's easier.
Make sure that main.tex compiles before submitting a pull request

**Comment by marikgoldstein** [comment]
Reminder: please make scribe notes!

**Comment by yaojiayu0826** [comment]
All three of us were not familiar with github. I just made a pull request, with lecture 16 notes added
