### ISSUE TITLE
Make Lecture 3 notes

### ISSUE THREAD

**Issue by rachtsingh** [harvard-ml-courses/cs281-scribe#4]
Just a reminder (no need to rush).

@christophermosch 
@ryanlapcevic
@lindseysbrown

As a walkthrough, you need to:
1. Make your own fork (so you can make a pull request).
2. Make a `3/` folder and include in it a copy of `2.tex -> 3.tex`
3. Edit `3.tex` with the lecture notes
4. Edit `main.tex` to add a reference to `3/3` (i.e. `3.tex` inside folder `3/`)  
5. Edit README.md to refer to the right place

Make sure `3/3.pdf` are compiled and committed, and `main.pdf` is recompiled.

**Comment by lindseysbrown** [comment]
So is the goal to have a total of one document that we all contribute to?

**Comment by rachtsingh** [comment]
Yep! Feel free to coordinate via ShareLatex if that's easier.

**Comment by ryanlapcevic** [comment]
Hi Christopher & Lindsey. I made a ShareLatex project and sent you invites. I'll post my notes later tonight. Thanks.

**Comment by ryanlapcevic** [comment]
It only let me add one collaborator so I made it public. Chris, you can access it [here](https://www.sharelatex.com/project/59b720ef665c5f740d46bc69).

**Comment by christophermosch** [comment]
Thanks, Ryan. Sorry, I saw Rachit’s email too late, I’m done with the notes (attached). I’m creating a pull request now. Feel free to make changes!

 

Chris

**Comment by lindseysbrown** [comment]
Can you upload your file to the sharelatex project before you do that so it's easier for Ryan and I to make edits?

**Comment by rachtsingh** [comment]
Chris fyi: I think you're responding from email notifications (from here: https://github.com/harvard-ml-courses/cs281-scribe/issues/4), and I don't think we can see the attachment.

**Comment by christophermosch** [comment]
Here we go. Thanks, Rachit.
[Lecture3.pdf](https://github.com/harvard-ml-courses/cs281-scribe/files/1294379/Lecture3.pdf)

**Comment by lindseysbrown** [comment]
Looks really good, but what about the tex file so that we can make edits?

**Comment by christophermosch** [comment]
Uploading .tex here is not supported. I'm trying to figure out how to put it into the ShareLatex folder.

**Comment by lindseysbrown** [comment]
If you go into the project, there's an option to upload right under menu.  Alternatively, if you email the files to me (lindsey_brown@g.harvard.edu), I can upload them if that's easier.

**Comment by christophermosch** [comment]
Cool, thanks. Sent it to you. Somehow the upload button wasn't working for me.

**Comment by lindseysbrown** [comment]
Got it and files are uploaded to the share latex project.

**Comment by lindseysbrown** [comment]
Ryan, I'll leave a comment here when I'm done with my edits, and then you can put in the pull request with your edits.  Chris, thanks for all your work getting this done so efficiently!

**Comment by ryanlapcevic** [comment]
Sounds good, thanks Lindsey. Really nice work, Chris.

**Comment by lindseysbrown** [comment]
I just finished my edits - I added the examples we discussed from the beginning of class but beyond that just a few minor notes/changes.

**Comment by ryanlapcevic** [comment]
Cool thanks. I'll post my changes and then submit the pull request. @rachtsingh do we need to submit separate pull requests for 'documentation' or just the one?

**Comment by rachtsingh** [comment]
Just one's fine.

**Comment by rachtsingh** [comment]
Hey, I just committed the stuff in the ShareLatex on your behalf, since I didn't get a PR. You're all set!
