### ISSUE TITLE
Make Lecture 17: Loopy BP and SVI

### ISSUE THREAD

**Issue by marikgoldstein** [harvard-ml-courses/cs281-scribe#40]
Hi all, just a reminder to make a pull request together for the lecture 17 notes, Loopy BP and SVI.

@dem123456789, Enmao Diao
@lpentecost, Lillian Pentecost
@tongbaojia, Baojia Tong
@AndreCJS, André Snoeck
@pvarin, Patrick Varin
@shuanno, Hsuan Lee 

You'll want to:

Make sure you read the LaTeX Guide
Make your own fork (so you can make a pull request when submitting).
Make a 17/ folder, include in it a copy of 16.tex, and rename it to 17.tex
(use a previous one if 16.tex is not up yet)
Edit 17.tex with the lecture notes
**Place all of your added commands + libraries in pagesetup.sty in the main directory**
Edit main.tex to add a reference to 17/17 (i.e. 17.tex inside folder 17/)
Edit README.md to refer to the right place
Feel free to discuss on here or on ShareLatex if that's easier.
**Make sure that main.tex compiles before submitting a pull request**

**Comment by pvarin** [comment]
Are you looking for a single PR or one from everyone?

@everyone, If we are submitting a single PR together I've created a fork we can submit to here. I'll give you all collaborator permissions.

**Comment by pvarin** [comment]
@marikgoldstein, cloning the original repo and compiling results in an empty document for me. Is this a problem you've seen before?

**Comment by AndreCJS** [comment]
Thanks for settings this up. I'll take the Gibbs Sampling section.

**Comment by AndreCJS** [comment]
Hi guys,
Could someone please update the file with the section on Gibbs Sampling (see attached) and add my name to the scribes list (André Snoeck)? I'm having some issues. 
Thanks,
André

[topic_model.pdf](https://github.com/harvard-ml-courses/cs281-scribe/files/1451938/topic_model.pdf)

[17_gibbs.txt](https://github.com/harvard-ml-courses/cs281-scribe/files/1451940/17_gibbs.txt)

**Comment by pvarin** [comment]
Done @AndreCJS

**Comment by pvarin** [comment]
I think we've covered everything. @tongbaojia, @dem123456789, and @shuanno can you guys go over the material and fill in any gaps or add graphics as you see fit? Otherwise we can PR soon.

**Comment by tongbaojia** [comment]
Hi guys, I added in two figures for the message passing. Otherwise, it is fine with me.

**Comment by pvarin** [comment]
Cool, I'm going to PR then.

**Comment by shuanno** [comment]
Hey guys sorry that I didn't get the chance to check my e-mail yesterday...I'll look through the material and find if there's anything I can improve. Sorry about that

**Comment by pvarin** [comment]
No worries :) we can merge any changes you make into the current PR

**Comment by shuanno** [comment]
Hi @pvarin thanks for the reply. I think the scribe is really good and I could only modify the abbreviations and some minor format. Can anyone help me do the pull request for my .tex file? I have some issue of github for a while today...
Thanks!

[17.tex.zip](https://github.com/harvard-ml-courses/cs281-scribe/files/1454877/17.tex.zip)

**Comment by pvarin** [comment]
@shuanno done!

**Comment by marikgoldstein** [comment]
Sorry I missed these comments. The repo was in a rough state because several people fell behind on scribing and there were merge conflicts. It'll be taken care of ASAP
