### ISSUE TITLE
Make Lecture 18: VAEs and GANs

### ISSUE THREAD

**Issue by marikgoldstein** [harvard-ml-courses/cs281-scribe#44]
Hi all, just a reminder to make a pull request together for the lecture 18 notes, Variational Auto-encoders and GANs

@msdels, Michael Els
@leizhixian-research, Zhixian Lei
@sallysun1220, Yuting Sun
@jeffjc97, Jeff Chang
@xinche, Xincheng You
@Srivatsan-Srinivasan, Srivatsan Srinivasan

You'll want to:

Make sure you read the LaTeX Guide
Make your own fork (so you can make a pull request when submitting).
Make a 18/ folder, include in it a copy of 17.tex, and rename it to 18.tex
(use a previous one if 17.tex is not up yet)
Edit 18.tex with the lecture notes
**Place all of your added commands + libraries in pagesetup.sty in the main directory**
Edit main.tex to add a reference to 18/18 (i.e. 18.tex inside folder 18/)
Edit README.md to refer to the right place
Feel free to discuss on here or on ShareLatex if that's easier.
**Make sure that main.tex compiles before submitting a pull request**

**Comment by Srivatsan-Srinivasan** [comment]
Hi everyone, 

I would suggest we have one shared document on sharelatex and then divide and conquer pieces.

**Comment by msdels** [comment]
Sounds good to me. Any preference on how to divide the sections?

**Comment by marikgoldstein** [comment]
Let me know if none of you have a sharelatex account that allows >2 collaborators.

**Comment by jeffjc97** [comment]
I can make a sharelatex for all of us - what are your sharelatex account
emails?

**Comment by msdels** [comment]
Thanks Jeffrey, please use mels@hbs.edu for me.

**Comment by xinche** [comment]
Hi Jeffrey,

My email is xincheyou@gmail.com for my account.

Thanks,
Xincheng

**Comment by sallysun1220** [comment]
Hi Jeffrey,

My account is sallysun1220@gmail.com <mailto:sallysun1220@gmail.com>

Thanks,
Yuting

**Comment by leizhixian-research** [comment]
Hello everyone,

My account: leizhixian.research@gmail.com

2017-11-09 16:57 GMT-05:00 sallysun1220 <notifications@github.com>:

> Hi Jeffrey,
>
> My account is sallysun1220@gmail.com <mailto:sallysun1220@gmail.com>
>
> Thanks,
> Yuting
>

**Comment by jeffjc97** [comment]
I added all of the base files and shared it with all of y'all - Srivatsan,
do you have a sharelatex account as well?

Best,
Jeff

**Comment by Srivatsan-Srinivasan** [comment]
sorry, mine is vatsan09@gmail.com

**Comment by jeffjc97** [comment]
Sent you an invite!

**Comment by Srivatsan-Srinivasan** [comment]
What is the division plan ? Also, if I open the sharelatex link, I only see the template files and not a common file where we all edit. I am new to sharelatex is there something I am missing ?

**Comment by leizhixian-research** [comment]
There is a 18.tex in 18 folder and actually I added what I recorded in the class

> 在 2017年11月12日，下午2:39，Srivatsan-Srinivasan <notifications@github.com> 写道：
> 
> What is the division plan ? Also, if I open the sharelatex link, I only see the template files and not a common file where we all edit. I am new to sharelatex is there something I am missing ?
> 
>

**Comment by Srivatsan-Srinivasan** [comment]
So shall the rest of us go through the same document and make incremental changes if any ?

**Comment by sallysun1220** [comment]
Hi,

I went through our latex and it looks well-organized. I added one flowchart in the first part. Please let me know if you guys feel some places we need to improve.

Yuting

**Comment by Srivatsan-Srinivasan** [comment]
Looks good to me too. Added a couple of links that explain the math in greater detail. ( The original paper and a tutorial paper)

**Comment by xinche** [comment]
I made a couple changes and added a new graph. Everything looks good to me.

**Comment by msdels** [comment]
Looks good to me too. I made a couple of minor tweaks to the text.

-Michael

**Comment by jeffjc97** [comment]
I also made a few changes and looked over the text. Seems good to me.

**Comment by marikgoldstein** [comment]
Please make a pull request when it is all set.

**Comment by jeffjc97** [comment]
I can go ahead and make a PR if everyone's okay with our current notes!

**Comment by rachtsingh** [comment]
Can someone please make a pull request? This should have been done a week ago at the very latest.

**Comment by jeffjc97** [comment]
The PR should be good now! Let me know if there's anything else we should
do.

**Comment by rachtsingh** [comment]
Finished.
