### ISSUE TITLE
Make Lecture 19 Notes: Monte Carlo Basics

### ISSUE THREAD

**Issue by marikgoldstein** [harvard-ml-courses/cs281-scribe#45]
Hi all, just a reminder to make a pull request together for the lecture 19 notes, Monte Carlo Basics

@jeffrey6557, Chang Liu
@jiafengkevinchen, Jiafeng Chen
@alexanderplin, Alexander Lin

You'll want to:

Make sure you read the LaTeX Guide
Make your own fork (so you can make a pull request when submitting).
Make a 19/ folder, include in it a copy of 18.tex, and rename it to 19.tex
(use a previous one if 18.tex is not up yet)
Edit 19.tex with the lecture notes
**Place all of your added commands + libraries in pagesetup.sty in the main directory**
Edit main.tex to add a reference to 19/19 (i.e. 19.tex inside folder 19/)
Edit README.md to refer to the right place
Feel free to discuss on here or on ShareLatex if that's easier.
Make sure that 19.tex and main.tex compile before submitting a pull request

**Comment by jiafengkevinchen** [comment]
Hey everyone, should we put everything in a sharelatex document?

**Comment by alexanderplin** [comment]
I think sharelatex only allows two editors at a time

**Comment by alexanderplin** [comment]
Hey Mark? Can we get a sharelatex group that can hold more than 2 people?
:) I think that is easier

**Comment by jeffrey6557** [comment]
Hi everyone, 

I created a Sharelatex account so multiple people can work on the same file: 

account name: cs281advancedmachinelearning@gmail.com 
password: Cs281AML

I also built out a base of my notes on the file. It would be great if others can add and polish it. 

Chang

**Comment by rachtsingh** [comment]
Hey, can you finish this by today? This should have been done a long time ago.

**Comment by jeffrey6557** [comment]
Hi Scribe teammates,

Let's finish this as soon as we can, and let me know if you have any trouble logging in Sharelatex. You should see "Scribe note 19" already set up with a base of my notes.
<img width="1259" alt="screen shot 2017-11-21 at 11 50 47 am" src="https://user-images.githubusercontent.com/9246300/33088124-5605558a-ceb2-11e7-856d-cfdfb7652342.png">
<img width="1255" alt="screen shot 2017-11-21 at 11 50 31 am" src="https://user-images.githubusercontent.com/9246300/33088125-5616c892-ceb2-11e7-8ef6-19725f34bd7d.png">

Just a suggestion, I'd imagine one of us can polish the paragraphs to ensure the flow of ideas and/or add context, one can provide some nice figures, and one/two of us correct my notes against theirs. And we are done! 

Chang

**Comment by rachtsingh** [comment]
Actually on discussion, I think there's no need for 5 people to help finish this. I'm taking @hixor (Hikari) @StefanSpataru (Stefan) off this - if you could instead do one of the edits that Mark talked about or solve a bug that I've marked as "enhancement / help wanted" then that'll be enough for credit. If I'm wrong and you've already worked together extensively to finish this let me know.

**Comment by hixor** [comment]
Hey, sorry for any confusion around this-- I dropped this course way back in October. I should have taken my name off of the scribe list, I see!

Sorry again!

Best,
Hikari

--

**Comment by jiafengkevinchen** [comment]
Integrated my notes. I think we are good to go modulo some figures / proofreading (not sure if they are strictly necessary)

**Comment by alexanderplin** [comment]
You guys basically finished the whole thing, I went ahead and added
additional notes to the intuition behind the sampling types since I thought
that might be useful.

**Comment by jiafengkevinchen** [comment]
Just submitted the pull request

**Comment by rachtsingh** [comment]
Done, thanks!
