### ISSUE TITLE
Make Lecture 21 Notes: Deep Learning in Health Care

### ISSUE THREAD

**Issue by rachtsingh** [harvard-ml-courses/cs281-scribe#50]
Hi all, a reminder to make a pull request together for the lecture 21 notes: Deep Learning in Health Care. Please have this finished in 2-3 days, though end of Thanksgiving break is fine.

@rdhara, Raghu Dhara
@fr0420, Rui Fang
@phyllisju, Phyllis Ju

You need to:

Make sure you read the LaTeX Guide
Make your own fork (so you can make a pull request when submitting).
Make a 21/ folder, include in it a copy of 20.tex, and rename it to 21.tex
(use a previous one if 20.tex is not up yet)
Edit 21.tex with the lecture notes
**Place all of your added commands + libraries in pagesetup.sty in the main directory**
Edit main.tex to add a reference to 21/21 (i.e. 21.tex inside folder 21/)
Edit README.md to refer to the right place
Feel free to discuss on here or on ShareLatex if that's easier.
Make sure that 21.tex and main.tex compile before submitting a pull request

**Comment by fr0420** [comment]
Hi Rachit, 

Just want to make sure, is Phyllis still in this course? I tried to look for his contact info on Canvas but it seems he is not in the cs281 students list.

**Comment by rachtsingh** [comment]
I think she might have dropped the course - I also checked Canvas.

**Comment by fr0420** [comment]
@rdhara Hi Raghu! I started out creating a fork and added 21/21.tex. Would you like to edit the tex file on Sharelatex together? If so, just let me know your email address so I can share the project with you. Thanks!

**Comment by rdhara** [comment]
Hi Rui,

My email is rdhara@college.harvard.edu. I'd be happy to work on the tex file on Sharelatex!

Raghu

**Comment by rachtsingh** [comment]
Hey, any updates? Could we have this finished by today / tomorrow?

**Comment by rdhara** [comment]
Sure - we can push this by class tomorrow!

**Comment by fr0420** [comment]
@rdhara Hey Raghu, I updated the notes today. It's almost done except for a few places to add some details. Please check the sharelatex project and we can discuss when it's ready to push.

**Comment by fr0420** [comment]
The pull request is up now! Let me know if there's any problem.
