### ISSUE TITLE
Make Lecture 5 Notes

### ISSUE THREAD

**Issue by artidoro** [harvard-ml-courses/cs281-scribe#8]
Hey I just made a sharelatex project so we can all work there. 
Luke what's your email, so I can invite you too?

@lukemelas
@artidoro
@demiguo

I think it would be best to divide the notes in three and each work on a separate part. We can then harmonize and double check that we included everything. A division that I think could work:

1. Naive Bayes
2. Bayesian naive Bayes (first part)
3. From: Naiming terms in Naive Bayes, until the end

Let me know what you think!
(I am starting to work on 1. Naive Bayes)

**Comment by artidoro** [comment]
Demi is doing the second part, I am done with the first part.

**Comment by lukemelas** [comment]
Hello,

I apologize for the late reply. I would be happy to do the third part!

My email is lmelaskyriazi@college.harvard.edu.

Best,
Luke

**Comment by artidoro** [comment]
Perfect! I just sent you the invite to the sharelatex project.

**Comment by lukemelas** [comment]
Great, thank you! I'll complete them tonight or tomorrow morning.

Best,
Luke

**Comment by rachtsingh** [comment]
bump! Just wanted to make sure this got done today. Thanks!

**Comment by demiguo** [comment]
Hi all,
I just updated our sharelatex!

**Comment by lukemelas** [comment]
Thanks Demi! I'm working on the final section of notes now -- I'll have
them on the ShareLaTeX document by tonight.

Best,
Luke

**Comment by artidoro** [comment]
Can you do a pull request on github? The sharelatex is not connected to the github, otherwise you can let me know when you are done, and I can do it.

**Comment by artidoro** [comment]
Ok just submitted pull request :)
Let us know if we need to add anything.

**Comment by rachtsingh** [comment]
Thanks!
